### PR TITLE
Add link to readme for script-based system testing approach

### PR DESCRIPTION
**Pull request by vacer25**
## Proposed Change

- Add short paragraph and link to my repository at the top of readme for system testing using a script-based system testing approach instead of pytest for anyone who may want to investigate this option.

## Why are you requesting this change?

- Noticed a few groups had issues getting the pytest framework to work at all.
- The script-based approach is somewhat more easily customizable IMO.

### CODE REVIEW

**Comment by steven-hh-ding** [comment]
looks good to me. thank you. how about pushing your repo in another branch, and update the link to that branch? So well can reduce the number of out-links (they tend to fail over time..)

**Comment by vacer25** [comment]
> 
> 
> looks good to me. thank you. how about pushing your repo in another branch, and update the link to that branch? So well can reduce the number of out-links (they tend to fail over time..)

Yeah I can do this tomorrow.

**Comment by steven-hh-ding** [comment]
okay I merge for now. and you make another one okay?

**Comment by vacer25** [comment]
> 
> 
> okay I merge for now. and you make another one okay?

Yes, that sounds good.
I will create another pull request once I move all the code to another branch in this repository.

**Pull request merged**
